# Generated by Django 2.1.5 on 2019-02-09 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
