# Generated by Django 2.2 on 2019-04-30 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20190430_1331'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relationshiptype',
            old_name='type',
            new_name='name',
        ),
    ]
