# Generated by Django 2.2 on 2019-05-10 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_populate_relationshiptype'),
        ('accounts', '0004_populate_profile_slugfield'),
    ]

    operations = [
    ]
