# Generated by Django 2.2 on 2019-05-10 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_merge_20190510_1316'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='relationship',
            unique_together={('sender', 'receiver', 'type')},
        ),
    ]
